/*
 * EditFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package DemoFrame;

import javax.swing.JOptionPane;

import DemoDao.Until;
import DemoDto.MyDto;

/**
 *
 * @author  __USER__
 */
public class EditFrame extends javax.swing.JFrame {

	private MyDto dto;//声明一个数据对象
	private Until dao;//声明一个数据库操作对象

	/** Creates new form EditFrame */
	public EditFrame(MyDto dto, Until dao) {
		this.dto = dto;
		this.dao = dao;
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField_name = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea = new javax.swing.JTextArea();
		jButton_ok = new javax.swing.JButton();
		jButton_del = new javax.swing.JButton();
		jButton_esc = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("\u67e5\u8be2");

		jLabel1.setText("\u6807\u9898\uff1a");

		jLabel2.setText("\u5185\u5bb9\uff1a");

		jTextArea.setColumns(20);
		jTextArea.setRows(5);
		jScrollPane1.setViewportView(jTextArea);

		jButton_ok.setText("\u786e\u5b9a");
		jButton_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_okActionPerformed(evt);
			}
		});

		jButton_del.setText("\u5220\u9664");
		jButton_del.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton_delActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});

		jButton_esc.setText("\u53d6\u6d88");
		jButton_esc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_escActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(43, 43, 43)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel2)
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jTextField_name,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				178,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				46,
																				46,
																				46)
																		.addComponent(
																				jButton_ok)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton_del)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton_esc))
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																548,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(29, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(42, 42, 42)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jTextField_name,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton_ok)
														.addComponent(
																jButton_del)
														.addComponent(
																jButton_esc))
										.addGap(32, 32, 32)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																207,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(45, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton_delActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		Until dao = new Until(dto);//声明一个until对象
		dao.deletepeople(jTextField_name.getText());
		this.jTextField_name.setText("");
		this.jTextArea.setText("");
	}

	private void jButton_escActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
		new MainFrame(new MyDto()).setVisible(true);
	}

	private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {
		//判断是否为空
		if (!jTextField_name.getText().equals("")) {
			try {
				dao.findstring(jTextField_name.getText());//数据库查找
				jTextArea.setText("内容：" + dto.getArrayList().get(1) + "\n"
						+ "时间：" + dto.getArrayList().get(2));//显示查找的内容在文本框里
			} catch (Exception e1) {
				JOptionPane.showMessageDialog(null, "查无记录");//信息提示框
			}
		} else {
			JOptionPane.showMessageDialog(null, "输入错误");//信息提示框
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton_del;
	private javax.swing.JButton jButton_esc;
	private javax.swing.JButton jButton_ok;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea;
	private javax.swing.JTextField jTextField_name;
	// End of variables declaration//GEN-END:variables

}